remote: origin
target-branch: main
check-version-increment: true
validate-maintainers: false
validate-chart-schema: true
validate-yaml: true
chart-yaml-schema: configs/chart_schema.yaml
lint-conf: configs/yamllint.yaml
