checks:
  doNotAutoAddDefaults: false
  exclude: []
  include:
    - no-liveness-probe
    - no-readiness-probe
    - no-rolling-update-strategy
    - default-service-account
    - non-isolated-pod
    - minimum-three-replicas
    - cluster-admin-role-binding
    - access-to-secrets
    - read-secret-from-env-var
